function(target_set_warnings TARGET ENABLE ENABLE_AS_ERRORS)
    if (NOT ENABLE)
        C_MESSAGE(FG_RED "Compiler warnings are disabled for target ${TARGET}")
        return()
    else()
        C_MESSAGE(FG_GREEN "Enabling compiler warnings for target `${TARGET}`")
    endif()

    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        if (ENABLE)
            target_compile_options(${TARGET} PRIVATE -Wall -Wextra -Wpedantic)
        endif()
        if (ENABLE_AS_ERRORS)
            target_compile_options(${TARGET} PRIVATE -Werror)
        endif()
    elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        if (ENABLE)
            target_compile_options(${TARGET} PRIVATE /W4 /permissive-)
        endif()
        if (ENABLE_AS_ERRORS)
            target_compile_options(${TARGET} PRIVATE /WX)
        endif()
    else()
        message(WARNING "Unsupported compiler for setting warnings: ${CMAKE_CXX_COMPILER_ID}")
    endif()

endfunction()
