function (add_sanitizer_flags target)
    if (NOT ENABLE_ADDRESS_SANITIZER AND NOT ENABLE_THREAD_SANITIZER AND NOT ENABLE_UNDEFINED_BEHAVIOR_SANITIZER)
        message(FG_YELLOW "No sanitizers enabled, skipping sanitizer flags for target ${target}.")
        return()
    endif()

    if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        add_compile_options("-fno-omit-frame-pointer")
        add_link_options("-fno-omit-frame-pointer")

        if (ENABLE_ADDRESS_SANITIZER)
            add_compile_options("-fsanitize=address")
            add_link_options("-fsanitize=address")
        endif()

        if (ENABLE_THREAD_SANITIZER)
            add_compile_options("-fsanitize=thread")
            add_link_options("-fsanitize=thread")
        endif()

        if (ENABLE_UNDEFINED_BEHAVIOR_SANITIZER)
            add_compile_options("-fsanitize=undefined")
            add_link_options("-fsanitize=undefined")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        if (ENABLE_ADDRESS_SANITIZER)
            add_compile_options("/fsanitize=address")
            add_link_options("/fsanitize=address")
        endif()
        if (ENABLE_THREAD_SANITIZER)
            add_compile_options("/fsanitize=thread")
            add_link_options("/fsanitize=thread")
        endif()
        if (ENABLE_UNDEFINED_BEHAVIOR_SANITIZER)
            add_compile_options("/fsanitize=undefined")
            add_link_options("/fsanitize=undefined")
        endif()
    else()
        message(WARNING "Unsupported compiler for sanitizers: ${CMAKE_CXX_COMPILER_ID}. Skipping sanitizer flags for target `${target}`.")
    endif()
endfunction()
