string(ASCII 27 Esc)

set(RED "${Esc}[31m")
set(GREEN "${Esc}[32m")
set(YELLOW "${Esc}[33m")
set(BLUE "${Esc}[34m")
set(MAGENTA "${Esc}[35m")
set(CYAN "${Esc}[36m")
set(WHITE "${Esc}[37m")
set(BOLD "${Esc}[1m")
set(UNDERLINE "${Esc}[4m")
set(BG_RED "${Esc}[41m")
set(BG_GREEN "${Esc}[42m")
set(BG_WHITE "${Esc}[47m")
set(RESET "${Esc}[0m")


# Colored message wrapper
# Usage: C_MESSAGE FG_RED BG_WHITE BOLD Your message here
function(C_MESSAGE)
	# iterate over ARGV, collect color tokens then the rest is the message
	set(_seq "")
	set(_i 0)
	list(LENGTH ARGV _len)
	while(${_i} LESS ${_len})
		list(GET ARGV ${_i} _arg)
		string(TOUPPER "${_arg}" _u)
		if(_u STREQUAL "FG_RED")
			set(_seq "${_seq}${RED}")
		elseif(_u STREQUAL "FG_GREEN")
			set(_seq "${_seq}${GREEN}")
		elseif(_u STREQUAL "FG_YELLOW")
			set(_seq "${_seq}${YELLOW}")
		elseif(_u STREQUAL "FG_BLUE")
			set(_seq "${_seq}${BLUE}")
		elseif(_u STREQUAL "FG_MAGENTA")
			set(_seq "${_seq}${MAGENTA}")
		elseif(_u STREQUAL "FG_CYAN")
			set(_seq "${_seq}${CYAN}")
		elseif(_u STREQUAL "FG_WHITE")
			set(_seq "${_seq}${WHITE}")
		elseif(_u STREQUAL "BG_RED")
			set(_seq "${_seq}${BG_RED}")
		elseif(_u STREQUAL "BG_GREEN")
			set(_seq "${_seq}${BG_GREEN}")
		elseif(_u STREQUAL "BG_WHITE")
			set(_seq "${_seq}${BG_WHITE}")
		elseif(_u STREQUAL "BOLD")
			set(_seq "${_seq}${BOLD}")
		elseif(_u STREQUAL "UNDERLINE")
			set(_seq "${_seq}${UNDERLINE}")
		elseif(_u STREQUAL "RESET")
			set(_seq "${_seq}${RESET}")
		else()
			break()
		endif()
		math(EXPR _i "${_i} + 1")
	endwhile()

	# remaining args form the message
	set(_msg "")
	while(${_i} LESS ${_len})
		list(GET ARGV ${_i} _part)
		if(_msg STREQUAL "")
			set(_msg "${_part}")
		else()
			set(_msg "${_msg} ${_part}")
		endif()
		math(EXPR _i "${_i} + 1")
	endwhile()

	if(_msg STREQUAL "")
		# nothing to print
		return()
	endif()

	message("${_seq}${_msg}${RESET}")
endfunction()
